### ISSUE TITLE
Fatal error: Uncaught exception 'Google_Auth_Exception'

### ISSUE THREAD

**Issue by Dr34ml4and3r** [rapidwebltd/php-google-contacts-v3-api#36]
I installed the script with composer( composer require rapidwebltd/php-google-contacts-v3-api ) in the directory "google_contacts".After the google send the auth code and redirects me to the "redirect-handler.php" I receive this message.

Fatal error: Uncaught exception 'Google_Auth_Exception' with message 'Error fetching OAuth2 access token, message: 'invalid_client'' in /google_contacts/vendor/google/apiclient/src/Google/Auth/OAuth2.php:126 Stack trace: #0 /google_contacts/vendor/google/apiclient/src/Google/Client.php(128): Google_Auth_OAuth2->authenticate('4/98FDtobndj_Yx...', false) #1 /google_contacts/vendor/rapidwebltd/php-google-contacts-v3-api/helpers/GoogleHelper.php(76): Google_Client->authenticate('4/98FDtobndj_Yx...') #2 /google_contacts/vendor/rapidwebltd/php-google-contacts-v3-api/redirect-handler.php(19): rapidweb\googlecontacts\helpers\GoogleHelper::authenticate(Object(Google_Client), '4/98FDtobndj_Yx...') #3 {main} thrown in /google_contacts/vendor/google/apiclient/src/Google/Auth/OAuth2.php on line 126

**Comment by Dr34ml4and3r** [comment]
I managed to find the cause of this error.It was my bad, in client secret field(from config.json) I entered the path to the file client_secret.You need the enter only the code from the API.
